### ISSUE TITLE
"matches any" searchSelector possible?

### ISSUE THREAD

**Issue by tliebig** [NeXTs/Jets.js#2]
Hey Denis,

jets.js seems like a really *really* handy filter tool for big lists - one thing we've come quite accustomed to from both the OS X finder and Windows Explorer.

You wouldn't be able to implement the "matches any" filter - so that searching for searching for "Bar Wil" would still match "Barry Williamson" by taking the search phrase as independend key words instead of an entire phrase that must be machted?

This should be the CSS rule for that (if I'm right):
https://css-tricks.com/almanac/selectors/m/matches/

**Comment by shshaw** [comment]
A quick test showed that two (or more) `not` selectors would accomplish this.

`#jetsContent > :not([data-jets*="bar"]):not([data-jets*="wil"]) {display:none}`

`#jetsContent > :not([data-jets*="briggs"]):not([data-jets*="flo"]):not([data-jets*="bar"]) {display:none}`

http://codepen.io/shshaw/pen/EVPmpN

**Comment by NeXTs** [comment]
@shshaw Thank you for advice but it will find many rows that match even by one of two conditions ['bar', 'wil']

I believe @tliebig expects to get exact match by all conditions (or I'm wrong?) what can be accomplished by inverting CSS query to

```
#jetsContent > tr{ display: none };
#jetsContent > [data-jets*="bar"][data-jets*="wil"] {display:table-row}
```
http://codepen.io/NeXTs/pen/WQrOoQ

This is less universal solution to the general public because plugin don't know which display type should be applied to return it's to original state. It may be inline | block | inline-block | list | inline-list | rable-row | table-cell, etc...

But for your case, @tliebig, you know which type your rows are so can safely apply this rule.

**Comment by shshaw** [comment]
@tliebig said "matches any", which made it sound like `wil OR bar`. The double `:not` would be the way to go for that case.

If "matches all" is what's needed (`wil AND bar`), here's another way to accomplish that without having to specifically set the display:

```css
#jetsContent > :not([data-jets*="bar"]):not([data-jets*="wil"]),
#jetsContent > [data-jets*="wil"]:not([data-jets*="bar"]),
#jetsContent > [data-jets*="bar"]:not([data-jets*="wil"]) {display:none}
```

http://codepen.io/shshaw/pen/gaPRXV

This would get somewhat complex with more matches, but for this case it's not crazy.

**Comment by NeXTs** [comment]
@shshaw great idea  :+1:

**Comment by NeXTs** [comment]
@shshaw What if there will be 3 and more search phrases?
(wil AND bar AND go)

**Comment by tliebig** [comment]
How about for wil AND bar AND go:

**Comment by tliebig** [comment]
Sorry about closing and reopening the issue #fatfingers :)

**Comment by NeXTs** [comment]
@tliebig thank you. By the way, which behaviour you requested? AND or OR?

**Comment by tliebig** [comment]
I actually meant "AND". Sorry for not reponding to your question beforehand ;o)

On Di., Sep. 15, 2015 at 9:31 AM, Denis Lukov < notifications@github.com [notifications@github.com] > wrote:
@tliebig [https://github.com/tliebig] thank you. By the way, which behaviour you requested? AND or OR?

—
Reply to this email directly or view it on GitHub
[https://github.com/NeXTs/Jets.js/issues/2#issuecomment-140303627] .[https://github.com/notifications/beacon/AANLzqQ_pGneFsYa7LjrMrt9pmLqCooeks5ox79vgaJpZM4F9GbT.gif]

**Comment by shshaw** [comment]
This is the best I've been able to come up with. I can't find any selectors that would optimize this further.

```css
#jetsContent > :not([data-jets*="bar"]):not([data-jets*="wil"]):not([data-jets*="son"]),
#jetsContent > [data-jets*="wil"]:not([data-jets*="bar"]),
#jetsContent > [data-jets*="wil"]:not([data-jets*="son"]),
#jetsContent > [data-jets*="bar"]:not([data-jets*="wil"]),
#jetsContent > [data-jets*="bar"]:not([data-jets*="son"]),
#jetsContent > [data-jets*="son"]:not([data-jets*="wil"]),
#jetsContent > [data-jets*="son"]:not([data-jets*="bar"]) { display: none }
```

One rule with all of the `:not` rules to exclude items with no matches, then selectors for each item paired with a `:not` for every other item. More than three would be a massive selector, though you could declare each as an individual rule ( `#jetsContent > [data-jets*="son"]:not([data-jets*="wil"]) { display: none } #jetsContent > [data-jets*="son"]:not([data-jets*="bar"]) { display: none }`), which might speed up browser parsing.

http://codepen.io/shshaw/pen/epJRMG?editors=110 
I added a few items that would be false positives in there to help test

**Comment by shshaw** [comment]
Oh man. Just saw @tliebig's snippet. Yes, using individual `:not`s is the best way to do an AND rule.

```css
#jetsContent > :not([data-jets*="bar"]),
#jetsContent > :not([data-jets*="son"]),
#jetsContent > :not([data-jets*="wil"]) { display: none }
```
